[package]
name = "rust_crypto"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
# Releases: https://crates.io/crates/aes
aes = { version = "0.8.4", default-features = false }
# Releases: https://crates.io/crates/base64ct
base64ct = { version = "1.8.0", default-features = false, features = ["alloc"] }
# Releases: https://crates.io/crates/cbc
cbc = { version = "0.1.2", default-features = false, features = ["block-padding", "alloc"] }
# Releases: https://crates.io/crates/des
des = { version = "0.8.1", default-features = false }
# Releases: https://crates.io/crates/ed25519-dalek
ed25519-dalek = { version = "2.1.1", default-features = false }
# Releases: https://crates.io/crates/fips203
fips203 = { version = "0.4.3", default-features = false, features = ["ml-kem-768"] }
# Releases: https://crates.io/crates/libc
libc = { version = "0.2.183", default-features = false }
# Releases: https://crates.io/crates/md-5
md-5 = { version = "0.10.6", default-features = false }
# Releases: https://crates.io/crates/p256
p256 = { version = "0.13.2", default-features = false, features = ["ecdh", "ecdsa", "pkcs8", "pem"] }
# Releases: https://crates.io/crates/p384
p384 = { version = "0.13.1", default-features = false, features = ["ecdh", "ecdsa", "pkcs8", "pem"] }
# Releases: https://crates.io/crates/p521
p521 = { version = "0.13.3", default-features = false, features = ["ecdh", "ecdsa", "pkcs8", "pem"] }
# Releases: https://crates.io/crates/pkcs1
pkcs1 = { version = "0.7.5", default-features = false, features = ["pem"] }
# Releases: https://crates.io/crates/pkcs8
pkcs8 = { version = "0.10.2", default-features = false, features = ["pem", "encryption", "3des"] }
# Releases: https://crates.io/crates/poly1305
poly1305 = { version = "0.8.0", default-features = false }
# Releases: https://crates.io/crates/rsa
rsa = { version = "0.9.8", default-features = false, features = ["pem"] }
# Releases: https://crates.io/crates/sec1
sec1 = { version = "0.7.3", default-features = false, features = ["pem"] }
# Releases: https://crates.io/crates/sntrup761
sntrup761 = { version = "0.4.0", default-features = false, features = ["kgen", "ecap", "dcap", "std"] }
# Releases: https://crates.io/crates/num-bigint-dig
num-bigint-dig = { version = "0.8.6", default-features = false }
# Releases: https://crates.io/crates/rand_core
rand_core = { version = "0.6.4", default-features = false, features = ["getrandom"] }
# Releases: https://crates.io/crates/sha1
sha1 = { version = "0.10.6", default-features = false, features = ["oid"] }
# Releases: https://crates.io/crates/sha2
sha2 = { version = "0.10.9", default-features = false, features = ["oid"] }
# Releases: https://crates.io/crates/x25519-dalek
x25519-dalek = { version = "2.0.1", default-features = false }

[profile.release]
panic = "abort"
